### ISSUE TITLE
Counting wrong answers

### ISSUE THREAD

**Issue by PhilippImhof** [ethz-let/moodle-qtype_mtf#19]
Someone has already asked for this in #15 and the question has also been brought up in the comments section of this plugin's page in the Moodle plugin database:

It would be good to have an option on how wrong answers are to be counted. If wrong answers do not lead to a deduction, students who guess will, in average, get half of all the points awarded, because they have a 50% chance of getting a point and a 50% chance of losing nothing.

I can understand that you do not like penalties in this question type. But maybe you could agree that this _might_ be useful in _certain_ cases, of course combined with the possibility of not answering parts where one is not sure. The plugin, as it is now, makes it impossible to adapt to these situations. I would gladly prepare a PR with that functionality. However, if you already know that you will not allow this option in your plugin, that seems pointless. 

Hence my question: Could you imagine to add support for neutral answers (leaving the line blank) and negative points in case of wrong answers, if you don't have to do it yourself?

**Comment by tkorner** [comment]
Hi Philipp
Thanks for your message. I do see your argument. Thank you for your offer. Let me chat with my colleagues and get back to you as soon as possible.
Best regards
Thomas

**Comment by PhilippImhof** [comment]
Thanks for your reply. I guess you have not had the time to discuss this with your colleagues?

**Comment by tkorner** [comment]
Hi Philipp
Sorry for the delay. Now I had the chance to discuss the offer. Since our online assessment service strongly believes that negative points are not suitable for assessment, this has been a challenging discussion. 
But in the sense of open source we are delighted to accept your suggestion in general, so please continue the development and make a pull request.
Two prerequisites:
a) please make negative points activatable/deactivatable by admins (in the admin setting of the qtype).
b) the standard setting should be "no" for this setting.

Thanks and best regards
