### ISSUE TITLE
Add clear choice to mtf question type

### ISSUE THREAD

**Issue by NavidDaxon** [ethz-let/moodle-qtype_mtf#21]
Hi there I have issue with this question type
When the student select an answer (true or false) it couldnt undo it and leave it not answer how can I add clear choice to this type of question
Ps: I changed the subpoint grading method and I need to students possible to change their mind and clear the answer they given

**Comment by nexterday** [comment]
Hi, the selection is radio button, hence a selection can not be cleared (HTamL standard). In order to “reset” to no selection, we would need reset answers button which would apply to all selections or trigger reset based on double clicking on prior selection and it may cause further confusion. 

Let me check with @tkorner and @spillinge and come back to you.

**Comment by tkorner** [comment]
Dear @NavidDaxon 
MTF doesn't know the negative points at the moment. Therefore there doesn't need to be a clearing option. We didn't implement this to encourage students to choose. 
If you wish to submit this feature, we are open for integration as long it remains possible, as an admin, to turn this on/off.

Ps. The other question type ([Single Choice](https://github.com/ethz-let/moodle-qtype_sc) ) has this feature because we see there is a higher probability for chancers to get points.

**Comment by NavidDaxon** [comment]
Hi @tkorner and @nexterday 
I know default mtf question type doesn't have negative point and it wouldn't be a problem to choose the answers and go on
But I rewrite the subpoint methode and I added negative point by getting isanswered class value and write the negative point for this type of question by my self thats why Iam looking for a way that students could clear their choices like Single choice type 
Is there any way I could add a button or something that the student could clear or rest the radio button that choose before for each question or option
Thank you for responding.

**Comment by tkorner** [comment]
some weeks ago, @phillipImhof mentioned comparable plan in this issue: https://github.com/ethz-let/moodle-qtype_mtf/issues/19 . Probably you could work on that together? 
As mentioned there and above. We are happy to work on pull requests as long as there is the chance to use it without negative points by default.
